// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDCiLLyCliB8OhZx0olej7fPXblRJOnA',
    appId: '1:628336675553:web:40820880921e28a68585a0',
    messagingSenderId: '628336675553',
    projectId: 'ten-2022',
    authDomain: 'ten-2022.firebaseapp.com',
    storageBucket: 'ten-2022.appspot.com',
    measurementId: 'G-6C1W70W4P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3o68xhW_SFz6DbhurHWIFDw9c8xoukaU',
    appId: '1:628336675553:android:99bb4bff81496bc98585a0',
    messagingSenderId: '628336675553',
    projectId: 'ten-2022',
    storageBucket: 'ten-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirVbaNBAGmKLzT7H0kaO3HLjCAuvqlFY',
    appId: '1:628336675553:ios:5ff16feff116feed8585a0',
    messagingSenderId: '628336675553',
    projectId: 'ten-2022',
    storageBucket: 'ten-2022.appspot.com',
    iosClientId: '628336675553-s6mvpahvb2ua933sloucc05td5rjlfig.apps.googleusercontent.com',
    iosBundleId: 'com.example.tg2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirVbaNBAGmKLzT7H0kaO3HLjCAuvqlFY',
    appId: '1:628336675553:ios:5ff16feff116feed8585a0',
    messagingSenderId: '628336675553',
    projectId: 'ten-2022',
    storageBucket: 'ten-2022.appspot.com',
    iosClientId: '628336675553-s6mvpahvb2ua933sloucc05td5rjlfig.apps.googleusercontent.com',
    iosBundleId: 'com.example.tg2',
  );
}
